Repository Team-InIT/inIT_AOS, pull requests merged in 2022-06, with the labels that each got.

#65 [UI] #64 - wrtie message ui end
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/mypage/message/WriteMessageActivity.kt
  app/src/main/res/drawable-v24/selector_rectangle_gray_to_mint.xml
  app/src/main/res/drawable/ic__arrow_back_white.xml
  app/src/main/res/layout/activity_write_message.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🎨UI🎨

#67 [FEAT] #66 - add dialog
  .idea/misc.xml
  app/src/main/java/com/init_android/app/util/CustomDialog.kt
  app/src/main/res/drawable/inset_horizontal_58.xml
  app/src/main/res/drawable/rectangle_fill_white_border_black01_radius10.xml
  app/src/main/res/layout/dialog_yes_no.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#71 Feat/70 modify mypage link
  .idea/gradle.xml
  app/src/main/java/com/init_android/InitService.kt
  app/src/main/java/com/init_android/app/data/request/mypage/RequestModifyLink.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseModifyLink.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyLinkActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#73 [FEAT] #72 - modify basic info
  app/src/main/java/com/init_android/InitService.kt
  app/src/main/java/com/init_android/app/data/request/mypage/RequestModifyBasicInfo.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseModifyBasicInfo.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyBasicInfoActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#76 Feat/70 modify mypage link
  .idea/misc.xml
  app/src/main/java/com/init_android/app/ServiceCreator.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageProjectFragment.kt
  app/src/main/res/layout/activity_my_page_modify_link.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#78 [FEAT] #77 - memeber quit end
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/data/request/mypage/RequestQuit.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseQuit.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signup/BaseInfoTwoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signup/PersonalInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/RecoProjectViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/oepn/project/OpenProjectActivity.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#79 [UI] #75 feed view
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable-v24/test.png
  app/src/main/res/drawable/ic_feed_add.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/rectangle_fill_main_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_main_right_radius_10.xml
  app/src/main/res/drawable/rectangle_stroke_gray_radius_16.xml
  app/src/main/res/drawable/selector_login_btn.xml
  app/src/main/res/drawable/selector_sex_btn.xml
  app/src/main/res/drawable/selector_skill_right_btn.xml
  app/src/main/res/layout/activity_my_page_modify_stack.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_partner.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨

#83 Modify/63 modify write view
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/RequestAddProject.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/oepn/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/oepn/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/oepn/viewmodel/ProjectViewModel.kt
  app/src/main/res/drawable-xxhdpi/selector_check_box.xml
  app/src/main/res/drawable/ic_check_box_gray.xml
  app/src/main/res/drawable/ic_check_box_main.xml
  app/src/main/res/layout/activity_open_project.xml
  app/src/main/res/layout/activity_open_project_second.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠, 👻MODIFY👻

#84 UI/68 mypage stack view
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyStackActivity.kt
  app/src/main/res/drawable/selector_gray_to_mint_radius.xml
  app/src/main/res/layout/activity_my_page_modify_stack.xml
  app/src/main/res/layout/activity_open_project.xml
Labels: 🐻혜빈🐻, 🎨UI🎨

#86 [FEAT] #68 - open project server connection
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/mypage/RequestCountProject.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseCountProject.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageProjectFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page_project.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#91 Feat/87 custom bottom sheet
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/model/SelectableData.kt
  app/src/main/java/com/init_android/app/data/request/RequestFinishProject.kt
  app/src/main/java/com/init_android/app/data/response/ResponseFinishProject.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/write/FeedWritingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/MainViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/message/WriteMessageActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/SpinnerAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
  app/src/main/java/com/init_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/java/com/init_android/app/util/CustomDecoration.kt
  app/src/main/java/com/init_android/app/util/SelectAdapter.kt
  app/src/main/res/drawable/ic_checked.xml
  app/src/main/res/drawable/selector_text_gray_to_main.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_bottomsheet_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#93 UI/92 check partner view
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/AosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/DesignFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/GameFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/IosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/ServerFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/WebFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerTabAdapter.kt
  app/src/main/res/drawable/ic_email_main.xml
  app/src/main/res/drawable/rectangle_fill_black_radius_14.xml
  app/src/main/res/layout/activity_partner_check.xml
  app/src/main/res/layout/fragment_aos.xml
  app/src/main/res/layout/fragment_design.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_ios.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/layout/item_partner_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠, 🎨UI🎨

#94 UI/74 project detail view
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/project/RequestProjectDetail.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
  app/src/main/res/drawable/ic_check_box_gray.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_heart_border.xml
  app/src/main/res/drawable/ic_vertical_point.xml
  app/src/main/res/drawable/selector_heart.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠, 🎨UI🎨

#96 UI/95 write to do
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WriteToDoActivity.kt
  app/src/main/res/layout/activity_write_to_do.xml
  app/src/main/res/layout/item_to_do_partner_list.xml
Labels: 🐻혜빈🐻, 🎨UI🎨

#103 Modify/99 modify write logic
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/request/RequestAddProject.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/util/BindingAdapter.kt
  app/src/main/res/layout/activity_open_project_second.xml
  app/src/main/res/layout/activity_project_detail.xml
Labels: 🐻혜빈🐻, 👻MODIFY👻

#105 [FEAT] #104 - add server code
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/project/RequestApplyProject.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseApplyProject.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/MainViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#106 Feat/104 apply project server connection
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/util/BindingAdapter.kt
  app/src/main/res/layout/activity_open_project.xml
  app/src/main/res/layout/activity_project_detail.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#112 [MODIFY] #111 - modify dday background drawable
  .idea/misc.xml
  app/src/main/java/com/init_android/app/util/BindingAdapter.kt
  app/src/main/res/drawable/rectangle_fill_gray_radius_14.xml
  app/src/main/res/layout/item_rv_project.xml
  app/src/main/res/layout/item_vp_project.xml
Labels: 🐸지연🐸, 🎨UI🎨, 👻MODIFY👻

#116 UI/115 mypage project detail
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageProjectFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageReadyActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageUploadActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageZZimActivity.kt
  app/src/main/res/drawable-v24/rectangle_stroke_gray_a3_radius_10.xml
  app/src/main/res/drawable-v24/selector_rectangle_border_gray_to_mint.xml
  app/src/main/res/layout/activity_my_page_join.xml
  app/src/main/res/layout/activity_my_page_ready.xml
  app/src/main/res/layout/activity_my_page_upload.xml
  app/src/main/res/layout/activity_my_page_zzim.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🎨UI🎨

#118 Modify/114 modify total view
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/data/request/project/RequestProjectDetail.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ToDoMainActivity.kt
  app/src/main/res/drawable-v24/rectangle_fill_gray_a3_radius_10.xml
  app/src/main/res/layout/activity_partner_check.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/layout/activity_to_do_main.xml
  app/src/main/res/layout/fragment_aos.xml
  app/src/main/res/layout/fragment_design.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_ios.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/layout/item_partner_approve_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#119 Modify/107 modify mypage server connection
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseMyInfo.kt
  app/src/main/java/com/init_android/app/data/response/mypage/test.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🐻혜빈🐻, 🐞FIX🐞

#121 [FEAT] #120 - multpart end
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/response/ResponseUpdateProfile.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyProfileActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#123 Feat/122 project partner server connection
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/project/RequestProjectMember.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectMember.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
  app/src/main/res/layout/activity_partner_check.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/item_partner_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#129 Feat/125 check member
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/RequestAddProject.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseMyInfo.kt
  app/src/main/java/com/init_android/app/data/response/mypage/test.kt
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveAos.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveDesign.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveGame.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveIos.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApprovePlan.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveServer.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseApproveWeb.kt
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseProjectMember.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyProfileActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
  app/src/main/java/com/init_android/app/util/BindingAdapter.kt
  app/src/main/java/com/init_android/app/util/BitmapUtil.kt
  app/src/main/res/layout/activity_my_page_modify_profile.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/layout/fragment_aos.xml
  app/src/main/res/layout/fragment_design.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_ios.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/layout/item_partner_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#137 [FEAT] pull test
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/request/mypage/RequestModifyStack.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseModifyStack.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyStackActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/PartnerPageActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#139 Feat/138 approve project server connection
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageZZimActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/activity_partner_page.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#140 [FEAT] #138 - 수정사항 반영
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/res/layout/fragment_plan.xml
Labels: 🐻혜빈🐻, 🐞FIX🐞

#142 Fix/141 reflect qa
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/data/response/ResponseSignIn.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/MainViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyProfileActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyStackActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/message/WriteMessageActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_open_project_second.xml
  app/src/main/res/layout/activity_project_detail.xml
Labels: 🐻혜빈🐻, 🐞FIX🐞

#145 [FEAT] #143 - modify bottom sheet
  .idea/misc.xml
  app/src/main/java/com/init_android/app/presentation/ui/feed/write/FeedWritingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageReadyActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/message/WriteMessageActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerDesignAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerPlanAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/search/partner/SearchPartnerFragment.kt
  app/src/main/java/com/init_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/item_partner_design_list.xml
Labels: 🐻혜빈🐻, 🐞FIX🐞

#153 [FEAT] #152 - upload server connection end
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseUpload.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageUploadActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/adapter/UploadAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/item_upload_project.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#158 Feat/154 todo recyclerview
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/AosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/DesignTodoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/GameToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/IosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/PlanToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ServerToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ToDoMainActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WebToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WriteToDoActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/adapter/TodoTabAdapter.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/layout/activity_to_do_main.xml
  app/src/main/res/layout/activity_write_to_do.xml
  app/src/main/res/layout/fragment_aos_to_do.xml
  app/src/main/res/layout/fragment_design_to_do.xml
  app/src/main/res/layout/fragment_game_to_do.xml
  app/src/main/res/layout/fragment_ios_to_do.xml
  app/src/main/res/layout/fragment_plan_to_do.xml
  app/src/main/res/layout/fragment_server_to_do.xml
  app/src/main/res/layout/fragment_web_to_do.xml
  app/src/main/res/layout/item_to_do_list.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#160 Feat/159 splash and logo
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/ic_init.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#162 [FEAT] #161 - logout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#164 Feat/161 logout
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/res/drawable-xxhdpi/logo.png
  app/src/main/res/drawable-xxhdpi/logo_blue.png
  app/src/main/res/drawable/circle_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#166 Fix/143 modify logic
  app/build.gradle
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyBasicInfoActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyLinkActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
Labels: 🐻혜빈🐻

#170 [FEAT] #161 - team member approve
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/response/project/approve/ResponseProjectMember.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/AosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/GameFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/IosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerAosAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/PartnerIosAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/res/layout/item_partner_aos_list.xml
  app/src/main/res/layout/item_partner_ios_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#174 Feat/171 lookup to do
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/response/todo/ResponseAllToDo.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/FeedViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/write/FeedWritingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/AosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/DesignTodoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/GameToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/IosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/PlanToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ServerToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ToDoMainActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WebToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/adapter/ToDoPlanAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/adapter/ToDoPlanImageAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/viewmodel/ToDoViewModel.kt
  app/src/main/java/com/init_android/app/util/CustomBottomSheetDialog.kt
  app/src/main/res/layout/item_to_do_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#177 Feat/175 wrtie to do
  app/src/main/java/com/init_android/app/data/response/ResponseFinishProject.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/FeedViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/write/FeedWritingActivity.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#181 Feat/175-wrtie-to-do
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/data/request/todo/RequestToDoMember.kt
  app/src/main/java/com/init_android/app/data/request/todo/RequestWriteToDo.kt
  app/src/main/java/com/init_android/app/data/response/todo/ResponseToDoMember.kt
  app/src/main/java/com/init_android/app/data/response/todo/ResponseWriteToDo.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/PlanToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WriteToDoActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/viewmodel/ToDoViewModel.kt
  app/src/main/res/layout/activity_write_to_do.xml
  app/src/main/res/layout/item_to_do_partner_list.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#183 Fix/182 modify detail data source
  app/src/main/java/com/init_android/app/data/response/project/ResponseProjectDetail.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/res/layout/activity_project_detail.xml
Labels: 🐻혜빈🐻, 🐞FIX🐞

#185 Feat/184 evalutation server connection
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/response/mypage/ResponseEvaluation.kt
  app/src/main/java/com/init_android/app/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFeedFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageInfoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageModifyStackActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageProjectFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageRateFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageReadyActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageUploadActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageZZimActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/PartnerPageActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/adapter/RatingAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/AosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/DesignFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/GameFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/IosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PartnerCheckActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/ServerFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/WebFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/team/TeamReviewActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/adapter/ToDoPlanAdapter.kt
  app/src/main/res/drawable/ic_check_box_main.xml
  app/src/main/res/drawable/ic_checked.xml
  app/src/main/res/layout/activity_partner_page.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/layout/activity_team_review.xml
  app/src/main/res/layout/fragment_aos_to_do.xml
  app/src/main/res/layout/fragment_custom_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_design.xml
  app/src/main/res/layout/fragment_my_page_project.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/layout/fragment_server_to_do.xml
  app/src/main/res/layout/item_rating_list.xml
  app/src/main/res/layout/item_search_partner.xml
  app/src/main/res/layout/item_to_do_list.xml
  app/src/main/res/layout/item_upload_project.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#190 Feat/188 approve member server connection
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/AosFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/DesignFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyAosAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyDesignAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyGameAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyIosAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyPlanAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyServerAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyWebAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/viewmodel/ProjectViewModel.kt
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#193 Feat/188 approve member server connection
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/data/request/RequestAddFeed.kt
  app/src/main/java/com/init_android/app/data/response/todo/ResponseToDoMember.kt
  app/src/main/java/com/init_android/app/presentation/ui/feed/write/FeedWritingActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/PlanFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/OpenProjectSecondActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/project/ProjectDetailActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/AosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/DesignTodoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/GameToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/IosToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/PlanToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/ServerToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WebToDoFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/WriteToDoActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/todo/adapter/ToDoPlanAdapter.kt
  app/src/main/java/com/init_android/app/presentation/ui/search/recruitfinish/SearchRecruitFinishFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/search/recruiting/SearchRecruitingFragment.kt
  app/src/main/java/com/init_android/app/util/BindingAdapter.kt
  app/src/main/res/layout/activity_my_page_ready.xml
  app/src/main/res/layout/activity_my_page_upload.xml
  app/src/main/res/layout/activity_my_page_zzim.xml
  app/src/main/res/layout/activity_open_project.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/layout/activity_recommend_project.xml
  app/src/main/res/layout/fragment_aos.xml
  app/src/main/res/layout/fragment_design.xml
  app/src/main/res/layout/fragment_game.xml
  app/src/main/res/layout/fragment_ios.xml
  app/src/main/res/layout/fragment_plan.xml
  app/src/main/res/layout/fragment_server.xml
  app/src/main/res/layout/fragment_server_to_do.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/layout/item_rating_list.xml
  app/src/main/res/layout/item_rv_project.xml
  app/src/main/res/layout/item_team_list.xml
  app/src/main/res/layout/item_to_do_partner_list.xml
  app/src/main/res/layout/item_vp_project.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#195 [FEAT] #194 - modify view
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/init_android/app/data/InitService.kt
  app/src/main/java/com/init_android/app/data/ServiceCreator.kt
  app/src/main/java/com/init_android/app/presentation/ui/home/signin/SignInActivity.kt
  app/src/main/java/com/init_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/init_android/app/presentation/ui/open/partner/adapter/ready/ReadyPlanAdapter.kt
  app/src/main/res/drawable/ic_thumb_main.xml
  app/src/main/res/drawable/ic_thumb_white.xml
  app/src/main/res/drawable/selector_thumbs.xml
  app/src/main/res/layout/fragment_review_undone.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠
